spring:
  application:
    name: registration-service

  datasource:
    url: jdbc:mysql://localhost:3306/registration_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=utf8
    username: registration_user
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

course-service:
  base-url: ${COURSE_SERVICE_BASE_URL:http://localhost:8082}

jwt:
  secret: ${JWT_SECRET:CRS-Microservices-Secret-Key-Nam-3-Hoc-Ky-2026-Doi-Trong-Thuc-Te}
